[build]
builder = "NIXPACKS"
nixpacksConfigPath = "railway.pnpm.build.toml"

[deploy]
# region = "europe-west4"
runtime = "V2"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10