providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1722902622'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
PORT= '3000'
DATABASE_URI = '${{MongoDB.MONGO_PUBLIC_URL}}'
PAYLOAD_SECRET = '${{secret(32)}}'
PAYLOAD_PUBLIC_SERVER_URL = 'https://${{RAILWAY_PUBLIC_DOMAIN}}'
NEXT_PUBLIC_SERVER_URL = 'https://${{RAILWAY_PUBLIC_DOMAIN}}'
NEXT_PUBLIC_IS_LIVE = ''
PAYLOAD_PUBLIC_DRAFT_SECRET = '${{secret(32)}}'
NEXT_PRIVATE_DRAFT_SECRET = '${{secret(32)}}'
REVALIDATION_KEY = '${{secret(32)}}'
NEXT_PRIVATE_REVALIDATION_KEY = '${{secret(32)}}'

[phases.build]
dependsOn = ['install']
cmds = ['npm run build']
cacheDirectories = [
    '.next/cache',
    'node_modules/.cache',
]

[phases.install]
dependsOn = ['setup']
cmds = ['npm ci --legacy-peer-deps']
cacheDirectories = ['/root/.npm']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
    'nodejs_22',
    'npm-9_x',
]
nixLibs = ['gcc-unwrapped']
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = 'e05605ec414618eab4a7a6aea8b38f6fbbcc8f08'

[start]
cmd = 'npm run start'